# Importing necessary modules
import streamlit as st

# Header menu class
class HeaderMenu:
    """
    Hides the hamburger menu automatically generated by Streamlit.
    """

    # Method
    @classmethod
    def hide_menu(cls):
        """
        Hides the hamburguer menu automaticaally generated by Streamlit.
        """

        # Hiding humburguer menu
        hide_st_style = """
                    <style>
                    #MainMenu {visibility: hidden;}
                    footer {visibility: hidden;}
                    header {visibility: hidden;}
                    </style>
                    """
        st.markdown(hide_st_style, unsafe_allow_html=True)